SELECT 
    CAST("Type License" AS VARCHAR) as type_license,
    CAST("Company" AS VARCHAR) as company,
    CAST("Accepts Subsidy" AS VARCHAR) as accepts_subsidy,
    CAST("Year Round" AS VARCHAR) as year_round,
    CAST("Daytime Hours" AS VARCHAR) as daytime_hours,
    CAST("Star Level" AS VARCHAR) as star_level,
    CAST("Mon" AS VARCHAR) as mon,
    CAST("Tues" AS VARCHAR) as tues,
    CAST("Wed" AS VARCHAR) as wed,
    CAST("Thurs" AS VARCHAR) as thurs,
    CAST("Friday" AS VARCHAR) as friday,
    CAST("Saturday" AS VARCHAR) as saturday,
    CAST("Sunday" AS VARCHAR) as sunday,
    CAST("Primary Caregiver" AS VARCHAR) as primary_caregiver,
    CAST("Phone" AS VARCHAR) as phone,
    CAST("Email" AS VARCHAR) as email,
    CAST("Address1" AS VARCHAR) as address1,
    CAST("Address2" AS VARCHAR) as address2,
    CAST("City" AS VARCHAR) as city,
    CAST("State" AS VARCHAR) as state,
    CAST("Zip" AS INTEGER) as zip,
    CAST("Subsidy Contract Number" AS VARCHAR) as subsidy_contract_number,
    CAST("Total Cap" AS INTEGER) as total_cap,
    CAST("Ages Accepted 1" AS VARCHAR) as ages_accepted_1,
    CAST("AA2" AS VARCHAR) as aa2,
    CAST("AA3" AS VARCHAR) as aa3,
    CAST("AA4" AS VARCHAR) as aa4,
    CAST("License Monitoring Since" AS DATE) as license_monitoring_since,
    CAST("School Year Only" AS VARCHAR) as school_year_only,
    CAST("Evening Hours" AS VARCHAR) as evening_hours
FROM 
    raw_ok;